// src/components/tablature/TablatureMain.vue
<template>
    <div class="partition-tab-container">
        <div class="tab-header">
            <h3 class="tab-title">Tablature - Mesure {{ store.currentMeasure + 1 }}</h3>
            <div class="tuning-info">
                Accordage: {{ store.tuningDisplay }}
            </div>
        </div>

        <div class="tab-content">
            <TabContent />

            <TabMultiSelection />
        </div>

        <div class="tab-controls">
            <TabNavigation />
            <TabPlayback />
        </div>
    </div>
</template>

<script lang="ts" setup>
import { onBeforeUnmount, onMounted } from 'vue';
import { useTablatureStore } from '../../stores/tablatureStore';
import TabContent from './TabContent.vue';
import TabMultiSelection from './TabMultiSelection.vue';
import TabNavigation from './TabNavigation.vue';
import TabPlayback from './TabPlayback.vue';

const store = useTablatureStore();

// Initialiser le store
onMounted(() => {
    store.initializeMeasures();
});

// Nettoyer les ressources lors de la destruction du composant
onBeforeUnmount(() => {
    store.stopPlayback();
});
</script>

<style scoped lang="scss">
.partition-tab-container {
    display: flex;
    flex-direction: column;
    background-color: #2a2a2a;
    border-radius: 8px;
    padding: 15px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    color: #e0e0e0;

    .tab-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 10px;

        .tab-title {
            margin: 0;
            font-size: 1.2rem;
        }

        .tuning-info {
            font-size: 0.9rem;
            color: #aaa;
            font-family: monospace;
        }
    }

    .tab-content {
        flex: 1;
        overflow-y: auto;
        background-color: #333;
        border-radius: 4px;
        padding: 10px;
    }

    .tab-controls {
        margin-top: 15px;
        display: flex;
        flex-direction: column;
        gap: 10px;
    }
}

@media (min-width: 768px) {
    .tab-controls {
        flex-direction: row !important;
        justify-content: space-between;

        .measure-navigation,
        .playback-controls {
            flex: 1;
        }
    }
}
</style>

// src/components/tablature/TablatureMain.tsx
import React, { useEffect } from 'react'
import './TablatureMain.scss'
import { useTablatureStore } from '../../stores/useTablatureStore'
import TabContent from './TabContent'
import TabMultiSelection from './TabMultiSelection'
import TabNavigation from './TabNavigation'
import TabPlayback from './TabPlayback'

export default function TablatureMain() {
  const currentMeasure = useTablatureStore(s => s.currentMeasure)
  const tuningDisplay = useTablatureStore(s => s.tuningDisplay())
  const initializeMeasures = useTablatureStore(s => s.initializeMeasures)
  const stopPlayback = useTablatureStore(s => s.stopPlayback)

  useEffect(() => {
    initializeMeasures()
    return () => { stopPlayback() }
  }, [])

  return (
    <div className="partition-tab-container">
      <div className="tab-header">
        <h3 className="tab-title">Tablature - Mesure {currentMeasure + 1}</h3>
        <div className="tuning-info">Accordage: {tuningDisplay}</div>
      </div>

      <div className="tab-content">
        <TabContent />
        <TabMultiSelection />
      </div>

      <div className="tab-controls">
        <TabNavigation />
        <TabPlayback />
      </div>
    </div>
  )
}
